import "./globals.css";
import Navbar from '@/components/Navbar';
import Footer from "@/components/Footer";
import { Inter } from "next/font/google";  // Importamos la fuente Inter desde Google Fonts

// Configuramos la fuente Inter
const inter = Inter({
  subsets: ["latin"],  // Especifica el subconjunto (por ejemplo, latin)
  weight: ["400", "600", "700"],  // Puedes elegir los pesos de la fuente que necesitas
});

export const metadata = {
  title: "Cottonier srl",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>  
      <body>
        <header><Navbar /></header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
